<a href="https://colab.research.google.com/github/PaulodiasDeveloper/Estudo_Machine_Learning/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Learning

Há dois tipos principais de aprendizado de máquina: supervisionado e não supervisionado.

O aprendizado supervisionado precisa que tenha uma resposta clara, ou seja, os dados devem ter uma classificação. Por exemplo, se a pessoa é diabética ou não, se deve ou não comprar uma ação, se possui câncer ou não. No aprendizado supervisioando, o seu conjunto vem com a resposta que será utilizada como gabarito para o seu modelo.

O aprendizado não supervisionado não necessita de uma resposta clara, basta que ele apresente (geralmente) os grupos onde os dados estão presentes. Nesse tipo de aprendizado, não temos uma resposta, é mais uma separação dos dados, a resposta (rótulos/labels) é determinada pelo desenvolvedor.

## Importação das bibliotecas

In [ ]:
# Importas as bibliotecas
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Carregando e cisualizando os dados

In [ ]:
# Carrega os dados
iris = load_iris()

#Visualizar o que há dentro do conjunto
print(f'''Nomes das features (medidas): {iris.feature_names}
      Nomes das classes (spécies): {iris.target_names}''')

Nomes das features (medidas): ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
      Nomes das classes (spécies): ['setosa' 'versicolor' 'virginica']

In [ ]:
# Transformar em DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
    )
df['target'] = iris.target # 0=setpsa. 1=versicolor, 2=Virginica
df.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

# Separando os dados e a resposta

In [ ]:
x = df.drop('target', axis=1)
y = df['target']

In [ ]:
x

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

# Divisão dos daos de treino e de teste

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(
    x,
    y,
    test_size=0.2, # 20% dos dados serão destinados ao teste (igual a train_size=0.8)
    random_state=42 # garante que a divisão seja a mesma (reprodutibilidade)
    )

print(f'''Total de amostras: {len(x)}
Amostras de treino: {len(x_treino)}
Amostras de teste: {len(x_teste)}
''')

Total de amostras: 150
Amostras de treino: 120
Amostras de teste: 30

# Criando e treinando o modelo

In [ ]:
# Carregar o modelo (cru)
modelo = KNeighborsClassifier(n_neighbors=3)

# Treinar o modelo
modelo.fit(x_treino, y_treino)

print('Modelo treinado com sucesso!')

Modelo treinado com sucesso!

# Fazendo a previsão

In [ ]:
# Fazer as prevosões com os dados de teste
previsao = modelo.predict(x_teste)

# Analisar algumas previsões
print(f'Previsão: {previsao[:5]}')
print(f'Resposta reais: \n{y_teste[:5]}')

Previsão: [1 0 2 1 1]
Resposta reais:
73     1
18     0
118    2
78     1
76     1
Name: target, dtype: int64

# Validadndo a acurácia

In [ ]:
# Avaliar a performance
acuracia = accuracy_score(y_teste, previsao)
print(f'Acurácia do modelo: {acuracia: .2%}')

Acurácia do modelo:  100.00%